# Generated by Django 2.2.13 on 2020-07-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0012_index_additions'),
        ('eveuniverse', '0002_load_eveunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can access this app'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Killmail',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
                ('solar_system', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.EveEntity')),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='short name to identify this webhook', max_length=64, unique=True)),
                ('webhook_type', models.IntegerField(choices=[(1, 'Discord Webhook')], default=1, help_text='type of this webhook')),
                ('url', models.CharField(help_text='URL of this webhook, e.g. https://discordapp.com/api/webhooks/123456/abcdef', max_length=255, unique=True)),
                ('notes', models.TextField(blank=True, default=None, help_text='you can add notes about this webhook here if you want', null=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='whether notifications are currently sent to this webhook')),
                ('is_default', models.BooleanField(default=False, help_text='When true this webhook will be preset for newly created trackers')),
            ],
        ),
        migrations.CreateModel(
            name='KillmailPosition',
            fields=[
                ('killmail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='position', serialize=False, to='killtracker.Killmail')),
                ('x', models.FloatField(blank=True, default=None, null=True)),
                ('y', models.FloatField(blank=True, default=None, null=True)),
                ('z', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KillmailVictim',
            fields=[
                ('killmail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='victim', serialize=False, to='killtracker.Killmail')),
                ('damage_taken', models.BigIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KillmailZkb',
            fields=[
                ('killmail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='zkb', serialize=False, to='killtracker.Killmail')),
                ('location_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('hash', models.CharField(blank=True, default='', max_length=64)),
                ('fitted_value', models.FloatField(blank=True, default=None, null=True)),
                ('total_value', models.FloatField(blank=True, default=None, null=True)),
                ('points', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('is_npc', models.BooleanField(blank=True, default=None, null=True)),
                ('is_solo', models.BooleanField(blank=True, default=None, null=True)),
                ('is_awox', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name to identify tracker. Will be shown on alerts posts.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Brief description what this tracker is for. Will not be shown on alerts.')),
                ('identify_fleets', models.BooleanField(default=False, help_text='when true: kills are interpreted and shown as fleet kills')),
                ('exclude_high_sec', models.BooleanField(default=False, help_text='exclude killmails from high sec.Also exclude high sec systems in route finder for jumps from origin.')),
                ('exclude_low_sec', models.BooleanField(default=False, help_text='exclude killmails from low sec')),
                ('exclude_null_sec', models.BooleanField(default=False, help_text='exclude killmails from null sec')),
                ('exclude_w_space', models.BooleanField(default=False, help_text='exclude killmails from WH space')),
                ('min_attackers', models.PositiveIntegerField(blank=True, default=None, help_text='Require killmails to have at least given amount of attackers', null=True)),
                ('max_attackers', models.PositiveIntegerField(blank=True, default=None, help_text='Exclude killmails that exceed given amount of attackers', null=True)),
                ('max_jumps', models.PositiveIntegerField(blank=True, default=None, help_text='Exclude killmails which are more than x jumps awayfrom the origin solar system', null=True)),
                ('min_value', models.PositiveIntegerField(blank=True, default=None, help_text='Exclude killmails with a value below the given amount', null=True)),
                ('max_distance', models.FloatField(blank=True, default=None, help_text='Exclude killmails which are farer away from the origin solar system than the given distance in lightyears', null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, default=4, help_text="ignore killmails that are older than the given number in hours (sometimes killmails appear belated on ZKB - this feature ensures they don't create new alerts)", null=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='toogle for activating or deactivating a tracker')),
                ('exclude_attacker_alliances', models.ManyToManyField(blank=True, default=None, help_text='exclude killmails with attackers are from one of these alliances', related_name='exclude_attacker_alliances_set', to='eveonline.EveAllianceInfo')),
                ('origin_solar_system', models.ForeignKey(blank=True, default=None, help_text='Solar system to calculate ranges and jumps from. (usually the staging system).', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='eveuniverse.EveSolarSystem')),
                ('require_attackers_ship_groups', models.ManyToManyField(blank=True, default=None, help_text='exclude killmails where attackers are flying one of these ship groups', limit_choices_to={'eve_category_id': 6}, related_name='require_attackers_ship_groups_set', to='eveuniverse.EveGroup')),
                ('require_victim_alliances', models.ManyToManyField(blank=True, default=None, help_text='only include killmails where the victim belongs to one of these alliances', related_name='require_victim_alliances_set', to='eveonline.EveAllianceInfo')),
                ('required_attacker_alliances', models.ManyToManyField(blank=True, default=None, help_text='only include killmails with attackers from one of these alliances', related_name='required_attacker_alliances_set', to='eveonline.EveAllianceInfo')),
                ('webhook', models.ForeignKey(blank=True, default=None, help_text='Webhook URL for a channel on Discord to sent all alerts to', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='killtracker.Webhook')),
            ],
        ),
        migrations.CreateModel(
            name='TrackedKillmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_matching', models.BooleanField(db_index=True, default=None, null=True)),
                ('date_sent', models.DateTimeField(db_index=True, default=None, null=True)),
                ('attackers_count', models.PositiveIntegerField(db_index=True, default=None, help_text='Calculated number of attackers', null=True)),
                ('jumps', models.PositiveIntegerField(db_index=True, default=None, help_text='Calculated number of jumps from origin', null=True)),
                ('distance', models.FloatField(db_index=True, default=None, help_text='Calculated distance from origin in lightyears', null=True)),
                ('is_high_sec', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_low_sec', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_null_sec', models.BooleanField(db_index=True, default=None, null=True)),
                ('is_w_space', models.BooleanField(db_index=True, default=None, null=True)),
                ('killmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='killtracker.Killmail')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='killtracker.Tracker')),
            ],
        ),
        migrations.CreateModel(
            name='KillmailAttacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_done', models.BigIntegerField(blank=True, default=None, null=True)),
                ('is_final_blow', models.BooleanField(blank=True, default=None, null=True)),
                ('security_status', models.FloatField(blank=True, default=None, null=True)),
                ('alliance', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailattacker_alliance_set', to='eveuniverse.EveEntity')),
                ('character', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailattacker_character_set', to='eveuniverse.EveEntity')),
                ('corporation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailattacker_corporation_set', to='eveuniverse.EveEntity')),
                ('faction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailattacker_faction_set', to='eveuniverse.EveEntity')),
                ('killmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attackers', to='killtracker.Killmail')),
                ('ship_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailattacker_shiptype_set', to='eveuniverse.EveEntity')),
                ('weapon_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eveuniverse.EveEntity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='trackedkillmail',
            constraint=models.UniqueConstraint(fields=('tracker', 'killmail'), name='functional_key'),
        ),
        migrations.AddField(
            model_name='killmailvictim',
            name='alliance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailvictim_alliance_set', to='eveuniverse.EveEntity'),
        ),
        migrations.AddField(
            model_name='killmailvictim',
            name='character',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailvictim_character_set', to='eveuniverse.EveEntity'),
        ),
        migrations.AddField(
            model_name='killmailvictim',
            name='corporation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailvictim_corporation_set', to='eveuniverse.EveEntity'),
        ),
        migrations.AddField(
            model_name='killmailvictim',
            name='faction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailvictim_faction_set', to='eveuniverse.EveEntity'),
        ),
        migrations.AddField(
            model_name='killmailvictim',
            name='ship_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailvictim_shiptype_set', to='eveuniverse.EveEntity'),
        ),
    ]
