# Generated by Django 2.2.12 on 2020-05-17 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can access this app'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EveEntity',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(blank=True, choices=[('alliance', 'alliance'), ('character', 'character'), ('constellation', 'constellation'), ('corporation', 'corporation'), ('faction', 'faction'), ('inventory_type', 'inventory_type'), ('region', 'region'), ('solar_system', 'solar_system'), ('station', 'station')], default=None, max_length=16, null=True)),
                ('last_updated', models.DateTimeField(blank=True, db_index=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Killmail',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('solar_system', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='killtracker.EveEntity')),
            ],
        ),
        migrations.CreateModel(
            name='KillmailPosition',
            fields=[
                ('killmail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='position', serialize=False, to='killtracker.Killmail')),
                ('x', models.FloatField(blank=True, default=None, null=True)),
                ('y', models.FloatField(blank=True, default=None, null=True)),
                ('z', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KillmailZkb',
            fields=[
                ('killmail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='zkb', serialize=False, to='killtracker.Killmail')),
                ('location_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('hash', models.CharField(blank=True, default='', max_length=64)),
                ('fitted_value', models.FloatField(blank=True, default=None, null=True)),
                ('total_value', models.FloatField(blank=True, default=None, null=True)),
                ('points', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('is_npc', models.BooleanField(blank=True, default=None, null=True)),
                ('is_solo', models.BooleanField(blank=True, default=None, null=True)),
                ('is_awox', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KillmailAttacker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_done', models.BigIntegerField(blank=True, default=None, null=True)),
                ('is_final_blow', models.BooleanField(blank=True, default=None, null=True)),
                ('security_status', models.FloatField(blank=True, default=None, null=True)),
                ('alliance', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailattacker_alliance_set', to='killtracker.EveEntity')),
                ('character', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailattacker_character_set', to='killtracker.EveEntity')),
                ('corporation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailattacker_corporation_set', to='killtracker.EveEntity')),
                ('faction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailattacker_faction_set', to='killtracker.EveEntity')),
                ('killmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attackers', to='killtracker.Killmail')),
                ('ship_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailattacker_shiptype_set', to='killtracker.EveEntity')),
                ('weapon_type_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='killtracker.EveEntity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KillmailVictim',
            fields=[
                ('killmail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='victim', serialize=False, to='killtracker.Killmail')),
                ('damage_taken', models.BigIntegerField(blank=True, default=None, null=True)),
                ('alliance', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailvictim_alliance_set', to='killtracker.EveEntity')),
                ('character', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailvictim_character_set', to='killtracker.EveEntity')),
                ('corporation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailvictim_corporation_set', to='killtracker.EveEntity')),
                ('faction', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailvictim_faction_set', to='killtracker.EveEntity')),
                ('ship_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killmailvictim_shiptype_set', to='killtracker.EveEntity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
