# Generated by Django 2.2.12 on 2020-05-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, default=4, help_text="ignore killmails that are older than the given number in hours (sometimes killmails appear belated on ZKB - this feature ensures they don't create new alerts)", null=True),
        ),
    ]
