# Generated by Django 2.2.12 on 2020-05-17 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('killtracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='killmailattacker',
            old_name='weapon_type_id',
            new_name='weapon_type',
        ),
    ]
