# Generated by Django 3.1.4 on 2021-01-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("killtracker", "0002_big_feature_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracker",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Brief description what this tracker is for. Will not be shown on alerts.",
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="you can add notes about this webhook here if you want",
            ),
        ),
    ]
