# Generated by Django 2.2.12 on 2020-05-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killtracker', '0002_auto_20200517_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='short name to identify this webhook', max_length=64, unique=True)),
                ('webhook_type', models.IntegerField(choices=[(1, 'Discord Webhook')], default=1, help_text='type of this webhook')),
                ('url', models.CharField(help_text='URL of this webhook, e.g. https://discordapp.com/api/webhooks/123456/abcdef', max_length=255, unique=True)),
                ('notes', models.TextField(blank=True, default=None, help_text='you can add notes about this webhook here if you want', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='whether notifications are currently sent to this webhook')),
                ('is_default', models.BooleanField(default=False, help_text='When true this webhook will be preset for newly created trackers')),
            ],
        ),
    ]
