# Generated by Django 3.1.4 on 2020-12-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("killtracker", "0002_big_feature_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracker",
            name="color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional color for embed on Discord - #000000 / black means no color selected",
                max_length=7,
            ),
        ),
    ]
