# Generated by Django 2.2.13 on 2020-07-16 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('killtracker', '0002_auto_20200715_1958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackerKillmail',
            new_name='TrackedKillmail',
        ),
    ]
