# Generated by Django 4.0.3 on 2022-03-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("killtracker", "0004_django4_update"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evekillmailattacker",
            name="alliance",
        ),
        migrations.RemoveField(
            model_name="evekillmailattacker",
            name="character",
        ),
        migrations.RemoveField(
            model_name="evekillmailattacker",
            name="corporation",
        ),
        migrations.RemoveField(
            model_name="evekillmailattacker",
            name="faction",
        ),
        migrations.RemoveField(
            model_name="evekillmailattacker",
            name="killmail",
        ),
        migrations.RemoveField(
            model_name="evekillmailattacker",
            name="ship_type",
        ),
        migrations.RemoveField(
            model_name="evekillmailattacker",
            name="weapon_type",
        ),
        migrations.RemoveField(
            model_name="evekillmailposition",
            name="killmail",
        ),
        migrations.RemoveField(
            model_name="evekillmailvictim",
            name="alliance",
        ),
        migrations.RemoveField(
            model_name="evekillmailvictim",
            name="character",
        ),
        migrations.RemoveField(
            model_name="evekillmailvictim",
            name="corporation",
        ),
        migrations.RemoveField(
            model_name="evekillmailvictim",
            name="faction",
        ),
        migrations.RemoveField(
            model_name="evekillmailvictim",
            name="killmail",
        ),
        migrations.RemoveField(
            model_name="evekillmailvictim",
            name="ship_type",
        ),
        migrations.RemoveField(
            model_name="evekillmailzkb",
            name="killmail",
        ),
        migrations.DeleteModel(
            name="EveKillmail",
        ),
        migrations.DeleteModel(
            name="EveKillmailAttacker",
        ),
        migrations.DeleteModel(
            name="EveKillmailPosition",
        ),
        migrations.DeleteModel(
            name="EveKillmailVictim",
        ),
        migrations.DeleteModel(
            name="EveKillmailZkb",
        ),
    ]
