# Generated by Django 2.2.13 on 2020-07-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killtracker', '0004_auto_20200716_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='require_attackers_ship_groups',
            field=models.ManyToManyField(blank=True, default=None, help_text='exclude killmails where attackers are flying one of these ship groups', limit_choices_to={'eve_category_id': 6}, related_name='require_attackers_ship_groups_set', to='eveuniverse.EveGroup'),
        ),
    ]
