# Generated by Django 2.2.13 on 2020-07-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('killtracker', '0005_auto_20200716_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webhook',
            old_name='is_active',
            new_name='is_enabled',
        ),
    ]
