# Generated by Django 4.0.3 on 2022-03-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("killtracker", "0006_recreate_killmail_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evekillmailattacker",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
